MAKE_FILE_SETTING := settings

test:
	DJANGO_SETTINGS_MODULE='capricorn.settings.test' coverage run ./manage.py test

ftest:
	DJANGO_SETTINGS_MODULE='capricorn.settings.fasttest' coverage run ./manage.py test

lint:
	pylint capricorn

report:
	coverage report

release_zip:
	mkdir -p eb_releases
		@read -p "Enter branch name:" branch; \
			read -p "Enter the environment:" environment; \
				read -p "Enter version:" version; \
					git archive --format=zip $$branch > eb_releases/$$environment-$$version.zip; \
						echo The file: eb_releases/$$environment-$$version.zip generated!

runserver:
	python3.4 manage.py runserver 0.0.0.0:8000

runwds:
	npm run localserver

loaddata:
	sh config/etc/loaddata.sh

rm_migrations:
	find /var/www/capricorn -type d -regextype sed -regex "/var/www/capricorn/capricorn/apps/.*/migrations" -exec rm -rf {} \;
